services:
  postgres:
    image: postgres:17-alpine
    container_name: theway-postgres-1
    environment:
      POSTGRES_USER: the_way_user
      POSTGRES_PASSWORD: the_way_password
      POSTGRES_DB: the_way
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
